(setq magit-status-buffer-switch-function 'switch-to-buffer)

(set-face-background 'magit-item-highlight "#333333")
(set-face-background 'diff-file-header "#121212")
(set-face-foreground 'diff-context "#666666")
(set-face-foreground 'diff-added "#00cc33")
(set-face-foreground 'diff-removed "#ff0000")
; '(magit-file-header ((t (:foreground "violet"))) t)
; '(magit-hunk-header ((t (:foreground "blue"))) t)
; '(magit-header ((t (:foreground "cyan"))) t)
; '(magit-tag-label ((t (:background "blue" :foreground "orange"))) t)
; '(magit-diff-add ((t (:foreground "Green"))) t)
; '(magit-diff-del ((t (:foreground "Red"))) t)
; '(magit-item-highlight ((t (:background "#333333"))) t)

(provide 'init-magit)
